---
kind: pipeline
type: docker
name: build
trigger: { event: [ push ] }
volumes: [ { name: docker, host: { path: "/data/ci-cache-docker" } } ]
image_pull_secrets: [ oci_hack_bg ] # https://docs.drone.io/pipeline/docker/syntax/images/#pulling-private-images
steps:

- name: prepare
  image: oci.hack.bg/platform-alpine:latest
  pull: always
  commands:
  - echo $HOME
  - ls -al $HOME
  - git config --global --add safe.directory /drone/src
  - printf $(git rev-parse --abbrev-ref HEAD) > "$HOME/BRANCH"
  - cat "$HOME/BRANCH"
  - git submodule update --init --recursive --depth 1

- name: docker
  image: oci.hack.bg/drone-docker:master
  pull: always
  volumes: [ { name: docker, path: "/var/lib/docker" } ]
  privileged: true
  settings:
    #debug:    true
    username: { from_secret: oci-user }
    password: { from_secret: oci-pass }
    registry: oci.hack.bg
    repo:     oci.hack.bg/undexer
    tags:     v4
