from rust:1.83-alpine3.21@sha256:9ab8f4eab808b1383c7e60a15fbf291e949fec85c3f98c34fb145b16c4ced0a1 as wasm
  run apk add musl-dev protoc protobuf-dev openssl-dev cmake build-base binaryen
  run rustup target add wasm32-unknown-unknown
  run cargo install wasm-pack@0.13.1
  workdir /build/fadroma-namada
  copy ./fadroma/packages/namada/Cargo.toml ./fadroma/packages/namada/Cargo.lock .
  run cat Cargo.toml && mkdir -p src && touch src/lib.rs && cargo fetch
  copy ./fadroma/packages/namada/src ./src
  run PATH=$PATH:~/.cargo/bin wasm-pack build --release --target web \
   && rm -rf target

from node:22.4-alpine3.20
  run apk add git
  workdir /app
  add . ./
  run pwd && ls -al
  run corepack install && corepack up && ~/.cache/node/corepack/v1/pnpm/10.0.0-rc.0/bin/pnpm.cjs i -P
  copy --from=wasm /build/fadroma-namada/pkg/fadroma_namada_bg.wasm ./fadroma/packages/namada/pkg/fadroma_namada_bg.wasm
  run pwd && ls -al
