FROM rust:1.83-alpine3.21@sha256:9ab8f4eab808b1383c7e60a15fbf291e949fec85c3f98c34fb145b16c4ced0a1 as wasm
  RUN apk add musl-dev protoc protobuf-dev openssl-dev cmake build-base binaryen
  RUN rustup target add wasm32-unknown-unknown
  RUN cargo install wasm-pack@0.13.1
  WORKDIR /build/fadroma-namada
  COPY ./fadroma/packages/namada/Cargo.toml ./fadroma/packages/namada/Cargo.lock .
  RUN cat Cargo.toml && mkdir -p src && touch src/lib.rs && cargo fetch
  COPY ./fadroma/packages/namada/src ./src
  RUN PATH=$PATH:~/.cargo/bin wasm-pack build --release --target web \
   && rm -rf target

FROM node:22.4-alpine3.20
  RUN apk add git
  WORKDIR /app
  ADD . ./
  RUN pwd && ls -al
  run corepack install && pnpm --version && corepack up && pnpm --version && pnpm i -P
  COPY --from=wasm /build/fadroma-namada/pkg/fadroma_namada_bg.wasm ./fadroma/packages/namada/pkg/fadroma_namada_bg.wasm
  RUN pwd && ls -al
